package View;

import Connection.ConnectionFactory;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.JOptionPane;

public class TelaBackup extends javax.swing.JFrame {

    Connection con = null;
    public TelaBackup() {
        initComponents();
        try{
            con = ConnectionFactory.conectar();
            //JFC_Salvar_Backup.setVisible(false);
            
            try {
                String arquivo = null;

                JFC_Salvar_Backup.setVisible(true);                        

                int result = JFC_Salvar_Backup.showSaveDialog(null);

                if(result == JFC_Salvar_Backup.APPROVE_OPTION){
                    arquivo = JFC_Salvar_Backup.getSelectedFile().toString().concat(".sql");

                    File file = new File(arquivo); 

                    if(file.exists()){
                        Object[] options = { "Sim", "Não" };
                        int opcao = JOptionPane.showOptionDialog(null,"Este arquivo já existe. Quer sobreescrever este arquivo?", "Atenção!!!",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,options, options[0]);
                        if (opcao == JOptionPane.YES_OPTION) {                
                            Runtime bck = Runtime.getRuntime();   
                            bck.exec("C:/Arquivos de Programas/MySQL/MySQL Server 8.0/bin/mysqldump.exe -v -v -v --host=localhost --user=root --password=Pedro@0704 --port=3306 --protocol=tcp --force --allow-keywords --compress  --add-drop-table --default-character-set=latin1 --hex-blob  --result-file="+arquivo+" --databases tst");  
                            JOptionPane.showMessageDialog(null, "Backup realizado com sucesso.", "Tudo OK!", 1);
                        }
                    }else{
                        Runtime bck = Runtime.getRuntime();   
                        bck.exec("C:/Arquivos de Programas/MySQL/MySQL Server 8.0/bin/mysqldump.exe -v -v -v --host=localhost --user=root --password=Pedro@0704 --port=3306 --protocol=tcp --force --allow-keywords --compress  --add-drop-table --default-character-set=latin1 --hex-blob  --result-file="+arquivo+" --databases tst");  
                        JOptionPane.showMessageDialog(null, "Backup realizado com sucesso.", "Tudo OK!", 1);   
                    }
                }
    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Erro!", 2);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e, "Erro!",2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFC_Salvar_Backup = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JFC_Salvar_Backup.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        JFC_Salvar_Backup.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                JFC_Salvar_BackupComponentRemoved(evt);
            }
        });
        JFC_Salvar_Backup.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                JFC_Salvar_BackupComponentHidden(evt);
            }
        });
        JFC_Salvar_Backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFC_Salvar_BackupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JFC_Salvar_Backup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JFC_Salvar_Backup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFC_Salvar_BackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFC_Salvar_BackupActionPerformed
        
    }//GEN-LAST:event_JFC_Salvar_BackupActionPerformed

    private void JFC_Salvar_BackupComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_JFC_Salvar_BackupComponentRemoved
      
    }//GEN-LAST:event_JFC_Salvar_BackupComponentRemoved

    private void JFC_Salvar_BackupComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_JFC_Salvar_BackupComponentHidden
         
    }//GEN-LAST:event_JFC_Salvar_BackupComponentHidden

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dispose();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBackup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser JFC_Salvar_Backup;
    // End of variables declaration//GEN-END:variables
}
